# Step 1: Modules caching
FROM golang:1.23.1-alpine3.20 AS modules
COPY go.mod go.sum /modules/
WORKDIR /modules
RUN go mod download

# Step 2: Builder
FROM golang:1.23.1-alpine3.20 AS builder
RUN go install github.com/air-verse/air@latest
COPY --from=modules /go/pkg /go/pkg
COPY . /app
WORKDIR /app

CMD ["air"]